language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli@0.1.13 karma-cli@0.0.4
  - gem install sass
script: grunt travis
sudo: false
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: AKIAI55AELZBPQKVIAXQ
  secret_access_key:
    secure: fDp97fUYc19sXmMnnp4OZL8MQYyTXRkxTVJj9NSdFI4xFCu34igwlcJXwHt9uuzV2wVIQ3R9GsAVfSwZxD+XWz1qrzWRt3PIsR5J7I9ZiqE0DaCK9IBVepsz5BR/A/q9v3VWGW7o+wy419EKVuXGHCJMAUoHeQCGeb8gOKYpI3g=
  bucket: ng-tags-input
  local-dir: build/travis
  skip_cleanup: true
  on:
    repo: mbenford/ngTagsInput
    branch: master
