name: ngTagsInput Site
markdown: kramdown
highlighter: rouge 
exclude: ['node_modules','*.log']
stable_version: 3.2.0
baseurl: /ngTagsInput

collections:
  pages:
    output: true
    permalink: /:path:output_ext

  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

feed:
  path: blog/feed.xml

author: Michael Benford

gems:
  - jekyll-feed