name: ngTagsInput Site
markdown: redcarpet
highlighter: pygments
exclude: ['node_modules','*.log']
stable_version: 3.1.1
baseurl: http://mbenford.github.io/ngTagsInput

collections:
  pages:
    output: true
    permalink: /:path:output_ext
